import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright-core';

const base = process.env.BASE_URL || 'http://127.0.0.1:60804/R4%20Muse%20V1';
const executablePath = process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch({ headless: true, executablePath });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.emulateMedia({ reducedMotion: 'reduce' });
await page.goto(base);
const axePath = new URL('./node_modules/axe-core/axe.min.js', import.meta.url).pathname;
await page.addScriptTag({ path: axePath });
await page.waitForFunction(() => !document.querySelector('.toast.show'));
const severeFindings = async () => (await page.evaluate(async () => axe.run(document, { runOnly: { type: 'tag', values: ['wcag2a','wcag2aa','wcag21a','wcag21aa'] } }))).violations.filter((v) => ['serious','critical'].includes(v.impact));
const checkTargets = async () => page.evaluate(() => [...document.querySelectorAll('button,input:not([type=checkbox]):not([type=radio]),select,textarea,[role=radio]')].filter((el) => { const r=el.getBoundingClientRect(); return !el.hidden && r.width > 0 && r.height > 0 && (r.width < 44 || r.height < 44); }).map((el) => el.outerHTML));
const settingsTrigger = page.getByRole('button', { name: 'settings' });
await settingsTrigger.click();
const dlg = page.getByRole('dialog');
assert.equal(await dlg.getAttribute('aria-modal'), 'true');
fs.mkdirSync('/Users/devin/shots/muse-brand', { recursive: true });
await page.screenshot({ path: '/Users/devin/shots/muse-brand/settings-slalom.png', fullPage: true });
assert.deepEqual(await severeFindings(), []);
assert.deepEqual(await checkTargets(), []);
await page.getByRole('radio', { name: 'AiGovOps' }).click();
await page.screenshot({ path: '/Users/devin/shots/muse-brand/settings-aigovops.png', fullPage: true });
assert.deepEqual(await severeFindings(), []);
assert.deepEqual(await checkTargets(), []);
await page.getByRole('button', { name: 'close' }).focus();
await page.keyboard.press('Tab');
assert.ok(await dlg.evaluate((el) => el.contains(document.activeElement)));
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(() => document.activeElement.getAttribute('aria-label')), 'settings');
await page.addStyleTag({ content: 'html{font-size:200%}' });
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
assert.deepEqual(await checkTargets(), []);
await page.getByRole('button', { name: 'close' }).click().catch(() => {});
await page.getByRole('button', { name: 'agents', exact: true }).click();
await page.screenshot({ path: '/Users/devin/shots/muse-brand/receipts.png', fullPage: true });
await browser.close();
console.log('Muse a11y ok: 390px, 200% text, modal focus, no serious/critical axe findings');
