import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';

const base = process.env.BASE_URL || 'http://127.0.0.1:60804/R4%20Muse%20V1';
const executablePath = process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const browser = await chromium.launch({ headless: true, executablePath });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.addInitScript(() => {
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text) => { window.__copied = text; } } });
});
const dismissAlert = async () => {
  const close = page.locator('[data-action="alert-close"]');
  if (await close.count()) await close.click({ force: true });
};
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto(base);
await dismissAlert();
assert.equal(await page.evaluate(() => document.documentElement.dataset.brand), 'slalom');
await page.getByRole('button', { name: 'settings' }).click();
const nameField = page.locator('[data-form="settings"] input[name="name"]');
await nameField.fill('Unsaved Brand Test');
const brandRadio = page.getByRole('radio', { name: 'AiGovOps' });
await dismissAlert();
await brandRadio.click();
assert.equal(await page.evaluate(() => document.documentElement.dataset.brand), 'aigovops');
assert.equal(await nameField.inputValue(), 'Unsaved Brand Test');
assert.equal(await brandRadio.evaluate((radio) => document.activeElement === radio), true);
await page.getByRole('button', { name: 'close' }).click();
await page.reload();
assert.equal(await page.evaluate(() => document.documentElement.dataset.brand), 'aigovops');
await dismissAlert();
await page.getByRole('button', { name: 'settings' }).click();
assert.notEqual(await page.locator('[data-form="settings"] input[name="name"]').inputValue(), 'Unsaved Brand Test');
await page.getByRole('button', { name: 'close' }).click();
await dismissAlert();
await page.getByRole('button', { name: 'agents', exact: true }).click();
await page.waitForTimeout(250);
const shareBase = await page.locator('meta[name="r4-share-base"]').getAttribute('content').catch(() => null);
await dismissAlert();
await page.locator('[data-action="agent-copy-link"]').click();
if (shareBase) assert.ok((await page.evaluate(() => window.__copied)).startsWith(shareBase));
assert.deepEqual(errors, []);
await browser.close();
console.log('Muse smoke ok: brand persistence, agents tab, no page errors');
